version: '3'
services:
  frontend:
    image: angular-app-production
    ports:
      - '4200:4200'
      # - '80:4200'
    networks:
      - mean-app
    restart: unless-stopped
  api-server:
    image: api-server
    env_file:
      - .env
    ports:
      - '5000:5000'
    networks:
      - mean-app
    depends_on: 
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mean-app
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
  nginx_reverseproxy:
    build:
      context: "nginx_reverseproxy"
      dockerfile: "Dockerfile"
    ports:
      - '80:80'
    networks:
      - mean-app
    restart: unless-stopped
networks:
  mean-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
